name = "Tex Hugo"
license = "MIT"
licenselink = "https://github.com/antonioalmeida/tex-hugo-theme/blob/master/LICENSE.md"
description = "Minimalistic website theme based on Tex's typography."
homepage = "https://github.com/antonio/tex-hugo-theme"
tags = ["tex", personal", "blog", "simple", "clean", "minimalist", "highlight.js", "bluma"]
features = ["html5", "css3", "highlight.js", "jssocials", "responsive"]
min_version = 0.46

[params]

[author]
  name = "António Almeida"
  homepage = "https://antonioalmeida/tex-hugo-theme"
