baseurl = "https://example.com"
languageCode = "en"
title = "Texugo"
theme = "tex-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/antonioalmeida\">António Almeida</a> 2020"
googleAnalytics = ""

[params]
    nickname = "johndoe"
    name = "John Doee"
    bio = ["Human being", "Not an animal", "a third thing"]

[[params.social]]
  name = "Github"
  url = "https://example.com"

[[params.social]]
  name = "Twitter"
  url = "https://example.com"

[[params.social]]
  name = "LinkedIn"
  url = "https://example.com"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4



